[package]
name = "llrp"
version = "0.1.0"
authors = ["Michael Chesser"]
edition = "2018"

[dependencies]
serde = { version = "1.0.91", features = ["derive"] }
crossbeam = "0.7.1"
byteorder = "1.3.1"
llrp-message = { path = "../llrp-message" }
llrp-common = { path = "../llrp-common" }