name: ci

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --manifest-path=./llrp/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path=./llrp/Cargo.toml --verbose
